---
title: "Manapouri Water Valuation Comparison"
subtitle: "Base (1931-2023) vs. New (1994-2023)"
author: "Benjamin Preston"
date: "2024-09-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tidyverse)

```


``` {r data_in}
# Load in WVs from full run (91 years + mean joiner)
# Load in WVs from alternate data set
# Run 0020 - 1931-2023 + joiner
# Run 0023 - 1931-1960 + joiner
# Run 0025 - 1941-1970 + joiner
# 

weeks <- 54
burnin <- 80

df <- read_csv("Apr24B_AVG_0011_WVX.csv", show_col_types = FALSE) |>  
  mutate(rn = row_number(),
         week = (rn - 1) %% (weeks + burnin) + 1,
         other_storage = floor((rn-1)/(weeks + burnin)),
         other_storage = round(other_storage / 12 * 100),
         ) |> 
  select(-rn) |> 
  pivot_longer(-c(week, other_storage), 
               names_to = "storage", values_to = "wv_base") |> 
  mutate(storage = round(as.double(storage)*100),
         wv_base = as.double(wv_base),
         os_label = paste0("OS", str_pad(other_storage, width = 3, pad = "0"))
         )

new <- read_csv("Apr24B_0018_WVX.csv", show_col_types = FALSE) |>  
  mutate(rn = row_number(),
         week = (rn - 1) %% (weeks + burnin) + 1,
         other_storage = floor((rn-1)/(weeks + burnin)),
         other_storage = round(other_storage / 12 * 100),
         ) |> 
  select(-rn) |> 
  pivot_longer(-c(week, other_storage), 
               names_to = "storage", values_to = "wv_new") |> 
  mutate(storage = round(as.double(storage)*100),
         wv_new = as.double(wv_new)
         )

## join the two data sets

if (dim(df)[1] != dim(new)[1]) {
  stop("Data sets are not the same length")
} else {
  df <- df |> 
    bind_cols(new[,"wv_new"]) 
}

```

## 
```{r storage, warning=FALSE}

week <- 1:(weeks-1)

wv <- 2^(0:12)

other_storage <- df |> 
  distinct(other_storage) |>
  arrange(other_storage) |>
  pull(other_storage)

storage_df <- expand_grid(week = week,
                       wv = wv,
                       other_storage = other_storage)


storage_base <- function(wv, week, other_storage) {
  # filter data by week and storage level
  filtered_df <- df |> 
    filter(week == !!week,
           other_storage == !!other_storage)
  
  # check that there are enough data points to interpolate
  if (nrow(filtered_df) < 2) {
    stop("Not enough data points to interpolate")
  }
  
  # interpolate the data using approx()
  storage_base <- approx(x = filtered_df$wv_base,
                                 y = filtered_df$storage,
                                 xout = wv, rule = 2)$y
  return(storage_base)
}

storage_new <- function(wv, week, other_storage) {
  # filter data by week and storage level
  filtered_df <- df |> 
    filter(week == !!week,
           other_storage == !!other_storage)
  
  # check that there are enough data points to interpolate
  if (nrow(filtered_df) < 2) {
    stop("Not enough data points to interpolate")
  }
  
  # interpolate the data using approx()
  storage_new <- approx(x = filtered_df$wv_new,
                                 y = filtered_df$storage,
                                 xout = wv, rule = 2)$y
  return(storage_new)
}




storage_df <- storage_df |> 
  mutate(stor_base = pmap_dbl(list(wv, week, other_storage), storage_base),
         stor_new = pmap_dbl(list(wv, week, other_storage), storage_new),
         stor_diff = stor_new - stor_base, 
         sq_stor_diff = stor_diff^2,
         os_label = paste0("OS", str_pad(other_storage, width = 3, pad = "0"))
         )

# Define %notin% operator
`%notin%` <- function(x, y) {
  !(x %in% y)
}


storage_df %>% 
  group_by(other_storage) %>%
  summarise(rmssd = sqrt(mean(sq_stor_diff))) %>% 
  ggplot(aes(x = other_storage, y = rmssd)) +
  geom_line()

storage_df %>% 
  group_by(week) %>%
  summarise(rmssd = sqrt(mean(sq_stor_diff))) %>% 
  ggplot(aes(x = week, y = rmssd)) +
  geom_line()


storage_df %>% 
  group_by(other_storage) %>%
  summarise(rmssd = sqrt(mean(sq_stor_diff))) %>% 
  print()

head(storage_df)

```


```{r contour, echo=FALSE}

df %>% 
  filter(week < 53,
         other_storage %in% c(50)
         ) |>
  ggplot() +
  geom_contour_filled(aes(x = week, y = storage, z = wv_base), breaks = wv) + # Base fill
  geom_contour(aes(x = week, y = storage, z = wv_new), color = "white", breaks = wv) +  # New line
  labs(title = "Manapouri Water Value Comparison",
       subtitle = "Mid Other Storage (OS) Level == 50",
       fill = "Water Values ($/MWh)",
       x = "Week",
       y = "Storage (0 - 100)") +
  facet_wrap(~os_label, nrow = 1) +
  theme_minimal()

df %>% 
  filter(week < 53,
         between(other_storage, 25, 75),
         other_storage != 50 # %in% c(25,33,42,58,67,75)
         ) |>
  ggplot() +
  geom_contour_filled(aes(x = week, y = storage, z = wv_base), breaks = wv) +
  geom_contour(aes(x = week, y = storage, z = wv_new), color = "white", breaks = wv) +  # Add contour lines for clarity
  labs(title = "Manapouri Water Value Comparison",
       subtitle = "Faceted by Inner Other Storage (OS) Levels [25, 75]",
       fill = "Water Values ($/MWh)",
       x = "Week",
       y = "Storage (0 - 100)") +
  facet_wrap(~os_label, nrow = 2) +
  theme_minimal()

df %>% 
  filter(week < 53,
         !between(other_storage, 25, 75) # %notin% c(25,33,42,50,58,67,75)
         ) |>
  ggplot() +
  geom_contour_filled(aes(x = week, y = storage, z = wv_base), breaks = wv) +
  geom_contour(aes(x = week, y = storage, z = wv_new), color = "white", breaks = wv) +  # Add contour lines for clarity
  labs(title = "Manapouri Water Value Comparison",
       subtitle = "Faceted by Outer Other Storage (OS) Levels",
       fill = "Water Values ($/MWh)",
       x = "Week",
       y = "Storage (0 - 100)") +
  facet_wrap(~os_label, nrow = 2) +
  theme_minimal()

```


```{r line, echo=FALSE}

storage_df |> 
  filter(week < 53,
         other_storage == 50
         ) |>
  ggplot(aes(x = week, y = stor_diff, group = wv)) +
  geom_line(aes(color = as.factor(wv))) +
  ylim(-100, 100) +
  labs(title = "Manapouri Storage Difference",
       subtitle = "Mid Other Storage (OS) Level == 50",
       x = "Week",
       y = "Storage Difference",
       color = "Water Values ($/MWh)") +
  facet_wrap(~os_label, nrow = 1)

storage_df |> 
  filter(week < 53,
         other_storage != 50,
         between(other_storage, 25, 75)
         ) |>
  ggplot(aes(x = week, y = stor_diff, group = wv)) +
  geom_line(aes(color = as.factor(wv))) +
  ylim(-100, 100) +
  labs(title = "Manapouri Storage Difference",
       subtitle = "Faceted by Inner Other Storage (OS) Levels [25, 75]",
       x = "Week",
       y = "Storage Difference",
       color = "Water Values ($/MWh)") +
  facet_wrap(~os_label, nrow = 2)

storage_df |> 
  filter(week < 53,
         !between(other_storage, 25, 75)
         ) |>
  ggplot(aes(x = week, y = stor_diff, group = wv)) +
  geom_line(aes(color = as.factor(wv))) +
  ylim(-100, 100) +
  labs(title = "Manapouri Storage Difference",
       subtitle = "Faceted by Outer Other Storage (OS) Levels",
       x = "Week",
       y = "Storage Difference",
       color = "Water Values ($/MWh)") +
  facet_wrap(~os_label, nrow = 2)

```


```{r rmssd, echo=FALSE}

inner_rmssd <- storage_df %>% 
  filter(week < 53,
         between(other_storage, 25, 75)) |>
  group_by(other_storage,week) %>%
  summarise(rmssd = sqrt(mean(sq_stor_diff)), .groups = "drop") |>
  pivot_wider(names_from = other_storage, values_from = rmssd) |>
  rename_with(
    .fn = ~ paste0("OS", str_pad(.x, width = 3, pad = "0")),
    .cols = -1
  ) |>
  mutate(Mean = rowMeans(across(-week))) %>% 
  pivot_longer(-week, names_to = "OS", values_to = "rmssd")

inner_rmssd |>
  filter(OS != "Mean") |>
  pull(rmssd) |>
  summary() |>
  print()

outer_rmssd <- storage_df %>% 
  filter(week < 53,
         !between(other_storage, 25, 75)) |>
  group_by(other_storage,week) %>%
  summarise(rmssd = sqrt(mean(sq_stor_diff)), .groups = "drop") |>
  pivot_wider(names_from = other_storage, values_from = rmssd) |>
  rename_with(
    .fn = ~ paste0("OS", str_pad(.x, width = 3, pad = "0")),
    .cols = -1
  ) |>
  mutate(Mean = rowMeans(across(-week))) %>% 
  pivot_longer(-week, names_to = "OS", values_to = "rmssd")

outer_rmssd |>
  filter(OS != "Mean") |>
  pull(rmssd) |>
  summary() |>
  print()

#Grand_Mean_RMSSD <- Summary_RMSSD[4] # pulls mean from summary output

inner_rmssd |>
  filter(OS != "Mean") %>% 
  ggplot(aes(x = week, y = rmssd, group = OS)) +
  geom_line(aes(color = "blue"),linewidth = .3) +
  geom_line(data = inner_rmssd %>% filter(OS == "Mean"), aes(x = week, y = rmssd),
            color = "black", linetype = "dashed", linewidth = 0.7) +
  #annotate("text", x = Inf, y = 15, label = "Weekly Mean (dashed)", hjust = 1.1, color = "black", size = 4) +
  #annotate("text", x = Inf, y = 14, label = "Grand Mean (solid)", hjust = 1.1, color = "black", size = 4) +
  #geom_hline(yintercept = Grand_Mean_RMSSD, color = "black", linewidth = 1) +
  labs(title = "Manapouri Root Mean Squared Storage Difference",
       subtitle = "by Week and Other Storage Level",
       x = "Week",
       y = "RMSSD",
       color = "Other Storage Levels") +
  theme_minimal()

```



